//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiftExchangeApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiftExchangeTable
    {
        public int Id { get; set; }
        public string Contents { get; set; }
        public string GiftHint { get; set; }
        public string WrappingPaperColor { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Depth { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<bool> IsOpened { get; set; }
    }

   

}
